"""Analyze and summarize metacatalog tables.

Logic to extract from ``notebooks/metacatalog_sky_view.ipynb`` and related QA
workflows (band coverage, association stats, sky selection helpers).
"""

from __future__ import annotations

from lwa_catalog.analyze.healpix_map import (
    metacatalog_to_healpix,
    metacatalog_to_hips,
    write_healpix_hips,
)
from lwa_catalog.analyze.nedlvs import (
    NedlvsMatchConfig,
    NedlvsMatchResult,
    build_sfr_radio_luminosity_table,
    load_nedlvs_catalog,
    match_catalog_to_nedlvs,
    radio_luminosity_nu,
    resolve_centroid_sigma_deg,
    resolve_highest_frequency_peak_flux,
    select_metacatalog,
    select_bijective_nedlvs_flags,
    select_unique_nedlvs_matches,
    summarize_nedlvs_match,
)
from lwa_catalog.analyze.reliability import (
    OR_HESL_EXCLUDE_FLAGS,
    OR_HESL_EXCLUDE_MASK,
    QualityFlagResult,
    ReliabilityConfig,
    ReliabilityResult,
    SourceQualityFlag,
    assert_gold_subset_of_cleaned,
    assign_source_quality_flags,
    decode_quality_flag,
    filter_by_quality_flags,
    filter_by_quality_mask,
    filter_metacatalog_exclude,
    filter_metacatalog_include,
    filter_metacatalog_reliability,
    filter_or_hesl,
    is_subband_metacatalog,
    quality_flag_bit_counts,
    quality_flag_legend,
    quality_flag_mask_from_names,
    quality_flag_names,
    representative_peak_flux,
)
from lwa_catalog.analyze.spectral import (
    SingleSpectrumFit,
    SpectralFitConfig,
    SpectralFitResult,
    fit_metacatalog_spectra,
    fit_single_spectrum,
    gather_band_flux_measurements,
    summarize_spectral_fit,
)
from lwa_catalog.analyze.summary import bands_present_counts, summarize_metacatalog
from lwa_catalog.analyze.trace import (
    SourceTrace,
    plot_maj_min_scatter,
    plot_member_property_scatter,
    plot_peak_flux_vs_lst,
    plot_ra_dec_scatter,
    preferred_trace_columns,
    rematch_meta_source,
)
from lwa_catalog.analyze.nvss import (
    NvssMatchConfig,
    NvssMatchResult,
    load_nvss_catalog,
    match_catalog_to_nvss,
    predict_flux_at_frequency_hz,
    select_unique_nvss_matches,
    summarize_nvss_match,
)
from lwa_catalog.analyze.vlass import (
    VlassMatchConfig,
    VlassMatchResult,
    load_vlass_catalog,
    match_catalog_to_vlass,
    select_unique_vlass_matches,
    summarize_vlass_match,
)
from lwa_catalog.analyze.vlssr import (
    VlssrMatchConfig,
    VlssrMatchResult,
    load_vlssr_catalog,
    match_catalog_to_vlssr,
    select_blue_associated_rows,
    summarize_vlssr_match,
)

__all__ = [
    "OR_HESL_EXCLUDE_FLAGS",
    "OR_HESL_EXCLUDE_MASK",
    "QualityFlagResult",
    "ReliabilityConfig",
    "ReliabilityResult",
    "SourceQualityFlag",
    "SourceTrace",
    "assign_source_quality_flags",
    "assert_gold_subset_of_cleaned",
    "bands_present_counts",
    "decode_quality_flag",
    "filter_by_quality_flags",
    "filter_by_quality_mask",
    "filter_metacatalog_exclude",
    "filter_metacatalog_include",
    "filter_metacatalog_reliability",
    "filter_or_hesl",
    "metacatalog_to_healpix",
    "metacatalog_to_hips",
    "plot_maj_min_scatter",
    "plot_member_property_scatter",
    "plot_peak_flux_vs_lst",
    "plot_ra_dec_scatter",
    "preferred_trace_columns",
    "quality_flag_bit_counts",
    "quality_flag_legend",
    "quality_flag_mask_from_names",
    "quality_flag_names",
    "rematch_meta_source",
    "representative_peak_flux",
    "is_subband_metacatalog",
    "summarize_metacatalog",
    "summarize_nedlvs_match",
    "summarize_nvss_match",
    "summarize_vlass_match",
    "summarize_vlssr_match",
    "write_healpix_hips",
    "VlssrMatchConfig",
    "VlssrMatchResult",
    "NvssMatchConfig",
    "NvssMatchResult",
    "VlassMatchConfig",
    "VlassMatchResult",
    "NedlvsMatchConfig",
    "NedlvsMatchResult",
    "build_sfr_radio_luminosity_table",
    "load_nedlvs_catalog",
    "load_nvss_catalog",
    "load_vlass_catalog",
    "load_vlssr_catalog",
    "match_catalog_to_nedlvs",
    "match_catalog_to_nvss",
    "match_catalog_to_vlass",
    "match_catalog_to_vlssr",
    "radio_luminosity_nu",
    "resolve_centroid_sigma_deg",
    "resolve_highest_frequency_peak_flux",
    "select_metacatalog",
    "select_bijective_nedlvs_flags",
    "select_unique_nedlvs_matches",
    "select_unique_nvss_matches",
    "select_unique_vlass_matches",
    "select_blue_associated_rows",
    "SingleSpectrumFit",
    "SpectralFitConfig",
    "SpectralFitResult",
    "fit_metacatalog_spectra",
    "fit_single_spectrum",
    "gather_band_flux_measurements",
    "predict_flux_at_frequency_hz",
    "summarize_spectral_fit",
]
